apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: kaniko-run
spec:
  taskRef:
    name: kaniko-chains
  params:
  - name: IMAGE
    value: gcr.io/priya-wadhwa/kaniko-chains
  workspaces:
  - name: source
    emptyDir: {}
  - name: dockerconfig
    secret:
      secretName: dockerconfig
