apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: kaniko-run-
spec:
  taskRef:
    name: kaniko-gcp
  params:
  - name: IMAGE
    value: gcr.io/ref-arch-wg/kaniko-chains-demo
  workspaces:
  - name: source
    emptyDir: {}
  - name: credentials
    secret:
      secretName: registry-credentials
